"""add can_reupload to documents

Revision ID: 9ec2599bb810
Revises: 2367b04c9206
Create Date: 2026-08-23 12:15:04.390959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec2599bb810'
down_revision: Union[str, None] = '2367b04c9206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('can_reupload', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'can_reupload')
    # ### end Alembic commands ###
