"""add_vehicle_taxes_charges_challans_and_fastag

Revision ID: ac4798419be6
Revises: ae458073031b
Create Date: 2026-09-04 13:15:59.459560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4798419be6'
down_revision: Union[str, None] = 'ae458073031b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_challans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('challan_number', sa.String(length=100), nullable=False),
    sa.Column('authority', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'OVERDUE', 'DISPUTED', name='challanstatus'), nullable=False),
    sa.Column('receipt_file_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='check_challan_amount_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_challans_challan_number'), 'vehicle_challans', ['challan_number'], unique=False)
    op.create_index(op.f('ix_vehicle_challans_id'), 'vehicle_challans', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_challans_status'), 'vehicle_challans', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_challans_vehicle_id'), 'vehicle_challans', ['vehicle_id'], unique=False)
    op.create_table('vehicle_fastags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('tag_number', sa.String(length=100), nullable=True),
    sa.Column('tag_provider', sa.String(length=100), nullable=True),
    sa.Column('tag_status', sa.Enum('ACTIVE', 'LOW_BALANCE', 'SUSPENDED', 'INACTIVE', name='fastagstatus'), nullable=False),
    sa.Column('linked_account_ref', sa.String(length=100), nullable=True),
    sa.Column('last_balance', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_fastags_id'), 'vehicle_fastags', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_fastags_vehicle_id'), 'vehicle_fastags', ['vehicle_id'], unique=True)
    op.create_table('vehicle_government_charges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('charge_type', sa.Enum('PERMIT_FEE', 'NATIONAL_PERMIT_FEE', 'STATE_PERMIT_FEE', 'OTHER_GOVERNMENT_CHARGE', name='chargetype'), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('authority', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DUE_SOON', 'OVERDUE', 'EXPIRED', 'PENDING', name='taxstatus'), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('receipt_file_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='check_charge_amount_non_negative'),
    sa.CheckConstraint('period_end >= period_start', name='check_charge_period_valid'),
    sa.CheckConstraint('valid_until >= valid_from', name='check_charge_validity_valid'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_government_charges_charge_type'), 'vehicle_government_charges', ['charge_type'], unique=False)
    op.create_index(op.f('ix_vehicle_government_charges_due_date'), 'vehicle_government_charges', ['due_date'], unique=False)
    op.create_index(op.f('ix_vehicle_government_charges_id'), 'vehicle_government_charges', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_government_charges_state'), 'vehicle_government_charges', ['state'], unique=False)
    op.create_index(op.f('ix_vehicle_government_charges_status'), 'vehicle_government_charges', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_government_charges_valid_until'), 'vehicle_government_charges', ['valid_until'], unique=False)
    op.create_index(op.f('ix_vehicle_government_charges_vehicle_id'), 'vehicle_government_charges', ['vehicle_id'], unique=False)
    op.create_table('vehicle_tax_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('tax_type', sa.Enum('ROAD_TAX', 'MOTOR_VEHICLE_TAX', 'ADDITIONAL_MOTOR_VEHICLE_TAX', 'STATE_VEHICLE_TAX', 'OTHER_TAX', name='taxtype'), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('tax_authority', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DUE_SOON', 'OVERDUE', 'EXPIRED', 'PENDING', name='taxstatus'), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('challan_number', sa.String(length=100), nullable=True),
    sa.Column('receipt_file_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='check_tax_amount_non_negative'),
    sa.CheckConstraint('period_end >= period_start', name='check_tax_period_valid'),
    sa.CheckConstraint('valid_until >= valid_from', name='check_tax_validity_valid'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_tax_records_due_date'), 'vehicle_tax_records', ['due_date'], unique=False)
    op.create_index(op.f('ix_vehicle_tax_records_id'), 'vehicle_tax_records', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_tax_records_state'), 'vehicle_tax_records', ['state'], unique=False)
    op.create_index(op.f('ix_vehicle_tax_records_status'), 'vehicle_tax_records', ['status'], unique=False)
    op.create_index(op.f('ix_vehicle_tax_records_tax_type'), 'vehicle_tax_records', ['tax_type'], unique=False)
    op.create_index(op.f('ix_vehicle_tax_records_valid_until'), 'vehicle_tax_records', ['valid_until'], unique=False)
    op.create_index(op.f('ix_vehicle_tax_records_vehicle_id'), 'vehicle_tax_records', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_tax_records_vehicle_id'), table_name='vehicle_tax_records')
    op.drop_index(op.f('ix_vehicle_tax_records_valid_until'), table_name='vehicle_tax_records')
    op.drop_index(op.f('ix_vehicle_tax_records_tax_type'), table_name='vehicle_tax_records')
    op.drop_index(op.f('ix_vehicle_tax_records_status'), table_name='vehicle_tax_records')
    op.drop_index(op.f('ix_vehicle_tax_records_state'), table_name='vehicle_tax_records')
    op.drop_index(op.f('ix_vehicle_tax_records_id'), table_name='vehicle_tax_records')
    op.drop_index(op.f('ix_vehicle_tax_records_due_date'), table_name='vehicle_tax_records')
    op.drop_table('vehicle_tax_records')
    op.drop_index(op.f('ix_vehicle_government_charges_vehicle_id'), table_name='vehicle_government_charges')
    op.drop_index(op.f('ix_vehicle_government_charges_valid_until'), table_name='vehicle_government_charges')
    op.drop_index(op.f('ix_vehicle_government_charges_status'), table_name='vehicle_government_charges')
    op.drop_index(op.f('ix_vehicle_government_charges_state'), table_name='vehicle_government_charges')
    op.drop_index(op.f('ix_vehicle_government_charges_id'), table_name='vehicle_government_charges')
    op.drop_index(op.f('ix_vehicle_government_charges_due_date'), table_name='vehicle_government_charges')
    op.drop_index(op.f('ix_vehicle_government_charges_charge_type'), table_name='vehicle_government_charges')
    op.drop_table('vehicle_government_charges')
    op.drop_index(op.f('ix_vehicle_fastags_vehicle_id'), table_name='vehicle_fastags')
    op.drop_index(op.f('ix_vehicle_fastags_id'), table_name='vehicle_fastags')
    op.drop_table('vehicle_fastags')
    op.drop_index(op.f('ix_vehicle_challans_vehicle_id'), table_name='vehicle_challans')
    op.drop_index(op.f('ix_vehicle_challans_status'), table_name='vehicle_challans')
    op.drop_index(op.f('ix_vehicle_challans_id'), table_name='vehicle_challans')
    op.drop_index(op.f('ix_vehicle_challans_challan_number'), table_name='vehicle_challans')
    op.drop_table('vehicle_challans')
    # ### end Alembic commands ###
