"""add reupload_requested and reupload_reason to documents

Revision ID: ae458073031b
Revises: 9ec2599bb810
Create Date: 2026-08-30 17:12:21.659429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae458073031b'
down_revision: Union[str, None] = '9ec2599bb810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('reupload_requested', sa.Boolean(), nullable=True))
    op.add_column('documents', sa.Column('reupload_reason', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_documents_reupload_requested'), 'documents', ['reupload_requested'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_reupload_requested'), table_name='documents')
    op.drop_column('documents', 'reupload_reason')
    op.drop_column('documents', 'reupload_requested')
    # ### end Alembic commands ###
